[package]
name = "geph4-client"
version = "4.7.5"
authors = ["nullchinchilla <nullchinchilla@pm.me>"]
edition = "2021"
description="Geph client"
license="GPL-3.0-only"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [patch.crates-io]
# sosistab2={path="../sosistab2"}

[lib]
name = "geph4client"
crate-type = ["staticlib", "lib"]

 
[dependencies]
anyhow = "1.0.68"
geph4-protocol= "0.13.0"

async-h1= "2.3.3"
bincode = "1.3.3"
flume = "0.10.14"
  
os_pipe = "1.1.2"
dirs = "3.0.2"
ed25519-dalek={ version = "1.0.1", features = ["serde"] }
futures-util= "0.3.26"
hex = "0.4.3"
http-types = "2.12.0"
log = "0.4.17"
once_cell= "1.17.0"
parking_lot = { version = "0.11.2", features = ["serde"] }
rand= "0.7.3"
regex = "1.7.1"
rsa-fdh = "0.5.0"

scopeguard = "1.1.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
sha2 = "0.9.9"
smol = "1.3.0"
smol-timeout = "0.6.0"
socksv5 = "0.2.0"

strsim = "0.10.0"
structopt = "0.3.26"
x25519-dalek={ version = "1.2.0", features = ["serde"] }
chrono = "0.4.23"

socket2= "0.3.19"
treebitmap={ package = "ip_network_table-deps-treebitmap", version = "0.5.0" }
pnet_packet= "0.27.2"
governor= "0.3.2"
async-dup= "1.2.2"
bytes= { version = "1.4.0", features = ["serde"] }
tap= "1.0.1"
smolscale= "0.3.52"
async-compat= "0.2.1"
im= "15.1.0"
event-listener= "2.5.3"
cached= "0.23.0"
rustls= "0.19.1"
webpki-roots= "0.21.1"
strip-ansi-escapes = "0.1.1"

geph-nat = "0.1.6"
mizaru = "0.1.3"
geph4-aioutils = "0.1.5"
# alloc_geiger = "0.1"

# socks2http
tokio = { version = "1.25.0", features = ["rt","net", "io-util"] }
hyper = { version = "0.14.23", features = ["http1", "client", "server", "tcp", "stream"] }
pin-project = "1.0.12"
http = "0.2.8"
psl = "2.1.3"
async-trait = "0.1.64"
tracing = "0.1.37"
env_logger = "0.9.3"
rlimit = "0.6.2"
binary-search = "0.1.2"
fastrand = "1.8.0"

nanorpc = "0.1.12"

native-tls={ version = "0.2.11", features = ["vendored"] }
itertools = "0.10.5"
whoami = "1.3.0"
tiny_http = "0.12.0"
thiserror = "1.0.38"
backoff = "0.4.0"
shutdown_hooks = "0.1.0"
libc = "0.2.139"
signal-hook = "0.3.14"
dashmap = "5.4.0"
default-net = "0.11.0"
eff-wordlist = "1.0.2"
blake3 = "1.3.3"
byteorder = "1.4.3"
smol_str = "0.1.23"
sosistab2 = "0.8.0"
stdcode = "0.1.14"
# jemallocator-global = "0.3.2"
panic-message = "0.3.0"
rusqlite = { version = "0.28.0", features = ["backup","bundled"] }
cap = "0.1.1"
colored = "2.0.0"
pad = "0.1.6"
futures-intrusive = "0.5.0"

# tracing-subscriber = "0.2.15"

[target.'cfg(unix)'.dependencies]
tun = "0.5.4"


[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["minwindef", "mmsystem", "timeapi"] }

[profile.dev]
panic = "unwind"
opt-level=1


[profile.release-dbg]
inherits="dev"
opt-level=3

[profile.release]
panic = "abort"
opt-level='z'
# debug=0
# lto=true
strip=true
# codegen-units = 1
