name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux-arm:
    name: basic building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: basics
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-gnu
      - name: super
        run: sudo su
          
      - name: compiling
        uses: actions-rs/cargo@v1
        with:
         use-cross: true
         command: build
         args: --release --locked --target aarch64-unknown-linux-gnu --manifest-path=Cargo.toml --target-dir /home/runner/gephy
        
      - name: tar the binary
        run: |
         export PROGRAM=/home/runner/gephy
         tar -cavf geph4arm.tar.gz $PROGRAM
         
      - uses: actions/upload-artifact@v3
        with:
          name: build-arm-artifact
          path: /home/runner/gephy/geph4arm.tar.gz
