name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: rust-cargo
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
    - uses: actions-rs/cargo@v1.0.1
    - run:  cargo build --release --locked --target aarch64-unknown-linux-gnu --manifest-path=geph4-client/Cargo.toml
