name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux-arm:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-gnu
      - uses: actions-rs/cargo@v1.0.1
        with:
          use-cross: true
          command: build
          args: --release --locked --target aarch64-unknown-linux-gnu --manifest-path=Cargo.toml --target-dir /tmp/geph4_build
      - name: export binaries
      - uses: actions/upload-artifact@v3
        with:
          name: Geph4-aarch64
          path: /tmp/geph4_build/project/target/release
